"""Named monitoring metrics backed by standard MIBs (not a full MIB compiler).

Operators build triggers against `name` fields. Collectors populate the same names
on DeviceMetricModel columns or extras.
"""

from __future__ import annotations

from typing import Any

METRIC_CATALOG: list[dict[str, Any]] = [
    {
        "name": "cpu_percent",
        "label": "CPU utilization",
        "mib": "HOST-RESOURCES-MIB",
        "oid": "1.3.6.1.2.1.25.3.3.1.2",
        "unit": "%",
        "kind": "gauge",
        "description": "Average hrProcessorLoad",
    },
    {
        "name": "memory_percent",
        "label": "Memory utilization",
        "mib": "HOST-RESOURCES-MIB",
        "oid": "1.3.6.1.2.1.25.2.3.1",
        "unit": "%",
        "kind": "gauge",
        "description": "RAM used from hrStorage table",
    },
    {
        "name": "uptime_seconds",
        "label": "System uptime",
        "mib": "SNMPv2-MIB",
        "oid": "1.3.6.1.2.1.1.3.0",
        "unit": "s",
        "kind": "counter",
        "description": "sysUpTime (converted from timeticks)",
    },
    {
        "name": "interfaces_total",
        "label": "Interfaces total",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.8",
        "unit": "count",
        "kind": "gauge",
        "description": "Count of interfaces in ifOperStatus walk",
    },
    {
        "name": "interfaces_down",
        "label": "Interfaces down",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.8",
        "unit": "count",
        "kind": "gauge",
        "description": "ifOperStatus == down (2)",
    },
    {
        "name": "if_in_errors",
        "label": "Interface in errors (sum)",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.14",
        "unit": "count",
        "kind": "counter",
        "description": "Sum of ifInErrors",
    },
    {
        "name": "if_out_errors",
        "label": "Interface out errors (sum)",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.20",
        "unit": "count",
        "kind": "counter",
        "description": "Sum of ifOutErrors",
    },
    {
        "name": "if_in_discards",
        "label": "Interface in discards (sum)",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.13",
        "unit": "count",
        "kind": "counter",
        "description": "Sum of ifInDiscards",
    },
    {
        "name": "if_out_discards",
        "label": "Interface out discards (sum)",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.19",
        "unit": "count",
        "kind": "counter",
        "description": "Sum of ifOutDiscards",
    },
    {
        "name": "if_in_octets",
        "label": "Interface in octets (sum)",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.10",
        "unit": "bytes",
        "kind": "counter",
        "description": "Sum of ifInOctets across interfaces",
    },
    {
        "name": "if_out_octets",
        "label": "Interface out octets (sum)",
        "mib": "IF-MIB",
        "oid": "1.3.6.1.2.1.2.2.1.16",
        "unit": "bytes",
        "kind": "counter",
        "description": "Sum of ifOutOctets across interfaces",
    },
    {
        "name": "if_in_bps",
        "label": "Ingress traffic rate",
        "mib": "IF-MIB (derived)",
        "oid": "derived",
        "unit": "bps",
        "kind": "gauge",
        "description": "Derived from consecutive ifInOctets samples",
    },
    {
        "name": "if_out_bps",
        "label": "Egress traffic rate",
        "mib": "IF-MIB (derived)",
        "oid": "derived",
        "unit": "bps",
        "kind": "gauge",
        "description": "Derived from consecutive ifOutOctets samples",
    },
    {
        "name": "temperature_c",
        "label": "Temperature",
        "mib": "ENTITY-SENSOR-MIB / vendor",
        "oid": "1.3.6.1.2.1.99.1.1.1.4 / vendor",
        "unit": "°C",
        "kind": "gauge",
        "description": "ENTITY-SENSOR celsius or MikroTik health OIDs",
    },
    {
        "name": "toner_percent",
        "label": "Printer toner level",
        "mib": "Printer-MIB",
        "oid": "1.3.6.1.2.1.43.11.1.1.9 / .8",
        "unit": "%",
        "kind": "gauge",
        "description": "prtMarkerSuppliesLevel / prtMarkerSuppliesMaxCapacity (primary/black marker)",
    },
    {
        "name": "paper_empty",
        "label": "Printer paper empty",
        "mib": "Printer-MIB",
        "oid": "1.3.6.1.2.1.25.3.5.1.2",
        "unit": "bool",
        "kind": "gauge",
        "description": "1 when hrPrinterDetectedErrorState reports a paper-out condition",
    },
    {
        "name": "rx_optical_dbm",
        "label": "SFP RX optical power",
        "mib": "vendor DOM (SFF-8472)",
        "oid": "vendor-specific",
        "unit": "dBm",
        "kind": "gauge",
        "description": "When exposed by vendor collector (transceiver digital optical monitoring)",
    },
    {
        "name": "tx_optical_dbm",
        "label": "SFP TX optical power",
        "mib": "vendor DOM (SFF-8472)",
        "oid": "vendor-specific",
        "unit": "dBm",
        "kind": "gauge",
        "description": "When exposed by vendor collector (transceiver digital optical monitoring)",
    },
]


def catalog_by_name() -> dict[str, dict[str, Any]]:
    return {m["name"]: m for m in METRIC_CATALOG}
